# Generated by Django 4.1.3 on 2022-11-15 23:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=255)),
                ('data_nascimento', models.DateTimeField(default=django.utils.timezone.now)),
                ('senha', models.CharField(max_length=255)),
            ],
        ),
    ]
