# Generated by Django 4.1.3 on 2022-11-16 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contato',
            name='senha',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
