# Generated by Django 4.1.3 on 2022-11-16 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_alter_contato_email_alter_contato_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='senha',
            field=models.CharField(max_length=255),
        ),
    ]
